name: Deploy to aliyun oss
on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # 设置阿里云OSS的 id/secret，存储到 github 的 secrets 中
      - uses: actions/checkout@master
      - name: setup aliyun oss
        uses: manyuanrong/setup-ossutil@v1.0
        with:
          endpoint: oss-cn-beijing.aliyuncs.com
          access-key-id: ${{ secrets.OSS_KEY_ID }}
          access-key-secret: ${{ secrets.OSS_KEY_SECRET }}
      - name: copy
        run: ossutil cp -rf ./ oss://website-zwc/
