name: Deploy to aliyun oss
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: checkout
        uses: actions/checkout@v2
        with:
          ref: master

      - name: setup aliyun oss
        uses: manyuanrong/setup-ossutil@v1.0
        with:
          endpoint: oss-cn-beijing.aliyuncs.com
          access-key-id: ${{ secrets.OSS_KEY_ID }}
          access-key-secret: ${{ secrets.OSS_KEY_SECRET }}

      - name: copy
        run: ossutil cp -rf ./content/ oss://website-zwc/ -u

# oosutil 用法
# https://help.aliyun.com/document_detail/179388.html?spm=a2c4g.11186623.6.845.7a1b5d22RORYl5

